spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 60s
