server:
  port: ${PRICE_STREAM_SERVICE_PORT:8084}
  shutdown: graceful

spring:
  datasource:
    url: ${PRICE_STREAM_DB_URL:jdbc:postgresql://postgres:5432/${POSTGRES_DB:tradex}}
    username: ${PRICE_STREAM_DB_USERNAME:${POSTGRES_USER}}
    password: ${PRICE_STREAM_DB_PASSWORD:${POSTGRES_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

springdoc:
  swagger-ui:
    enabled: false
